begin;

create type behavior_rating as enum ('Excellent', 'Good', 'Fair', 'Poor');
create type incident_type as enum ('Violence', 'Contraband', 'Escape Attempt', 'Health Emergency', 'Other');
create type severity_level as enum ('Low', 'Medium', 'High', 'Critical');
create type incident_status as enum ('Under Investigation', 'Resolved', 'Reported', 'Dismissed');
create type inmate_gender as enum ('Male', 'Female');
create type inmate_status as enum ('Active', 'Released', 'Transferred');
create type inmate_program_progress as enum ('Ongoing', 'Completed', 'Dropped');
create type medical_visit_type as enum ('Routine Checkup', 'Emergency', 'Follow-up', 'Mental Health', 'Other');
create type program_type as enum ('Educational', 'Vocational', 'Psychological', 'Other');
create type program_status as enum ('Active', 'Inactive', 'Completed', 'Cancelled');
create type release_reason as enum ('Sentence Completed', 'Parole', 'Other');
create type visitation_type as enum ('Conjugal Visit', 'Paduhol Visit', 'Visit to the Inmate');
create type visitation_status as enum ('Pending', 'Approved', 'Denied', 'Completed', 'Cancelled');
create type blood_type as enum ('A', 'B', 'AB', 'O');

create table if not exists roles (
  role_id integer generated by default as identity primary key,
  role_name varchar(50) not null
);

create table if not exists users (
  user_id integer generated by default as identity primary key,
  role_id integer not null references roles(role_id),
  username varchar(100) not null,
  email varchar(100) not null unique,
  password varchar(255) not null,
  created_at timestamptz not null default current_timestamp
);

create table if not exists profiles (
  profile_id integer generated by default as identity primary key,
  user_id integer not null unique references users(user_id) on delete cascade,
  firstname varchar(100),
  lastname varchar(100),
  contact_number varchar(20),
  address text,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create table if not exists visitors (
  visitor_id integer generated by default as identity primary key,
  user_id integer unique references users(user_id),
  relationship varchar(50)
);

create table if not exists inmates (
  inmate_id integer generated by default as identity primary key,
  first_name varchar(50),
  last_name varchar(50),
  birthdate date,
  gender inmate_gender not null,
  crime text,
  sentence_years integer,
  court_details text,
  cell_block varchar(50),
  admission_date date,
  release_date date,
  status inmate_status default 'Active',
  photo_path varchar(255),
  marital_status varchar(50),
  place_of_birth varchar(255),
  height varchar(50),
  weight varchar(50),
  hair_description varchar(100),
  complexion varchar(100),
  eyes_description varchar(100),
  citizenship varchar(100),
  religion varchar(100),
  race varchar(100),
  occupation varchar(255),
  no_of_children integer,
  permanent_address text,
  provincial_address text,
  educational_attainment varchar(100),
  course varchar(255),
  school_attended varchar(255),
  father_name varchar(255),
  father_address text,
  mother_name varchar(255),
  mother_address text,
  wife_clw_name varchar(255),
  wife_clw_address text,
  relative_name varchar(255),
  relative_address text,
  contact_number varchar(20),
  return_rate varchar(100),
  date_time_received timestamp,
  turned_over_by varchar(255),
  receiving_duty_officer varchar(255),
  offense_charged text,
  criminal_case_number varchar(255),
  case_court varchar(255),
  case_status varchar(100),
  prisoner_property text,
  property_receipt_number varchar(255),
  height_cm numeric(5,2),
  weight_kg numeric(5,2),
  blood_type blood_type,
  nationality varchar(100),
  eye_color varchar(50),
  hair_color varchar(50),
  identifying_marks text,
  emergency_contact_name varchar(100),
  emergency_contact_number varchar(20)
);

create table if not exists behavior_logs (
  log_id integer generated by default as identity primary key,
  inmate_id integer not null references inmates(inmate_id),
  staff_id integer not null references users(user_id),
  log_date date default current_date,
  notes text,
  behavior_rating behavior_rating default 'Fair'
);

create table if not exists incidents (
  incident_id integer generated by default as identity primary key,
  inmate_id integer not null references inmates(inmate_id),
  staff_id integer not null references users(user_id),
  incident_type incident_type default 'Other',
  severity_level severity_level default 'Low',
  location varchar(100),
  reported_by varchar(100),
  witnesses text,
  description text not null,
  action_taken text,
  status incident_status default 'Under Investigation',
  remarks text,
  incident_date timestamp default current_timestamp
);

create table if not exists programs (
  program_id integer generated by default as identity primary key,
  program_name varchar(100) not null,
  program_type program_type not null,
  description text,
  start_date date,
  end_date date,
  duration_weeks integer,
  capacity integer,
  location varchar(100),
  assigned_staff_id integer references users(user_id),
  status program_status default 'Active',
  requirements text
);

create table if not exists inmate_programs (
  inmate_program_id integer generated by default as identity primary key,
  inmate_id integer not null references inmates(inmate_id),
  program_id integer not null references programs(program_id),
  staff_id integer not null references users(user_id),
  start_date date,
  end_date date,
  progress inmate_program_progress default 'Ongoing'
);

create table if not exists medical_records (
  record_id integer generated by default as identity primary key,
  inmate_id integer not null references inmates(inmate_id),
  staff_id integer not null references users(user_id),
  visit_type medical_visit_type default 'Routine Checkup',
  diagnosis text,
  vital_signs text,
  blood_pressure varchar(10),
  temperature_c numeric(4,1),
  pulse_rate integer,
  respiratory_rate integer,
  treatment text,
  medication text,
  medical_condition varchar(255),
  allergies text,
  remarks text,
  next_checkup_date date,
  hospital_referred varchar(255),
  attachment_path varchar(255),
  record_date date default current_date
);

create table if not exists notifications (
  notification_id integer generated by default as identity primary key,
  user_id integer not null references users(user_id),
  title varchar(255) not null,
  message text not null,
  type varchar(50) default 'general',
  is_read boolean default false,
  created_at timestamptz not null default current_timestamp
);

create table if not exists releases (
  release_id integer generated by default as identity primary key,
  inmate_id integer not null references inmates(inmate_id),
  release_date date,
  reason release_reason not null,
  approved_by integer references users(user_id)
);

create table if not exists system_logs (
  log_id integer generated by default as identity primary key,
  action varchar(255) not null,
  details text,
  user_id integer references users(user_id),
  created_at timestamptz not null default current_timestamp,
  is_read boolean default false
);

create table if not exists transfers (
  transfer_id integer generated by default as identity primary key,
  inmate_id integer not null references inmates(inmate_id),
  from_block varchar(50),
  to_block varchar(50),
  transfer_date date,
  approved_by integer references users(user_id),
  reason text
);

create table if not exists visitations (
  visit_id integer generated by default as identity primary key,
  inmate_id integer not null references inmates(inmate_id),
  visitor_id integer not null references visitors(visitor_id),
  visit_type visitation_type default 'Visit to the Inmate',
  scheduled_date timestamp not null,
  status visitation_status default 'Pending',
  notes text,
  relationship varchar(100),
  created_at timestamptz not null default current_timestamp
);

insert into roles (role_id, role_name) values
  (1, 'Administrator'),
  (2, 'Correctional Officer'),
  (3, 'Medical Staff'),
  (4, 'Rehabilitation Staff'),
  (5, 'Visitor')
on conflict (role_id) do nothing;

select setval(
  pg_get_serial_sequence('roles', 'role_id'),
  greatest((select coalesce(max(role_id), 1) from roles), 1),
  true
);

create or replace function update_profiles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = current_timestamp;
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on profiles;
create trigger trg_profiles_updated_at
before update on profiles
for each row
execute function update_profiles_updated_at();

commit;
